sonar.projectKey=verk
sonar.projectName=verk
sonar.sources=cmd,internal,pkg
sonar.tests=cmd,internal,pkg
sonar.exclusions=**/testdata/**,**/*_test.go
sonar.test.exclusions=**/testdata/**
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out